# Configuration for mailman
# =================================================================

# IMAP Server to check for mails
mailcheck:
  # Username for login
  user: alexander.schilling@mycompany.de
  # Password for login
  password: mypass
  # Host or IP address to connect to
  host: mail.mycompany.de
  # Connection port
  port: 143
  # Secure login, set to true to login through TLS
  tls: false
  # TLS Upgrade decides when to upgrade to a secure session:
  # one of 'always', 'required', 'never'
  autotls: never
  # Connection timeout in milliseconds to wait to establish connection"
  connTimeout: 10s
  # Authentication timeout in milliseconds to wait to authenticate user"
  authTimeout: 5s

# Check interval to recheck for new emails in daemon mode
interval: 5m

# Commands
# -------------------------------------------------------------------
command:
  # Object of possible commands to use
  date:
    # Title and description used for the mail response
    title: "Get the Date"
    description: "Get the date from the server."
    # Filter rules which define the emails to react on
    filter:
      # case-insensitive part of the subject
      subject: 'what time is it'
      # address or list of addresses, also as case-insensitive parts
      from: '@mycompany.de'
    # Command to execute
    exec:
      # executional on command line
      cmd: 'date'
      # list of arguments
      args: []
    # response mail settings
    email:
      # use the template
      base: default

# Email Templates
# -------------------------------------------------------------------
email:
  default:
    # specify how to connect to the server
    transport: smtp://alexander.schilling%40mycompany.de:<<<env://PW_ALEX_DIVIBIB_COM>>>@mail.mycompany.de
    # sender address
    from: alexander.schilling@mycompany.de
    replyTo: alexander.schilling@mycompany.de

    # content
    locale: de
    subject: >
      Re: {{conf.title}}
    body: |+
      {{conf.title}}
      ==========================================================================

      {{conf.description}}

      Started on {{date date "LL"}} from {{date process.start "LTS"}} to {{date process.end "LTS"}}

      PID {{process.host}}#{{process.pid}}

      {{#if result.code}}
      ::: alert
      Code {{result.code}} {{result.error}}
      :::
      {{/if}}

      {{#if result.stdout}}
      ``` text
      {{result.stdout}}
      ```
      {{/if}}

      {{#if result.stderr}}
      ``` text
      {{result.stderr}}
      ```
      {{/if}}
